<script lang="ts">
	import { login } from '$lib/stores/auth';
	import Proto1 from '$lib/assets/images/proto-1.svg?url';
	import Segment from '$lib/components/landing/Segment.svelte';
	import Grid from '$lib/components/landing/Grid.svelte';
	import Button from '$lib/components/common/Button.svelte';

	// these arrays with text could be put in a own directory in future
	const howWorksArr = [
		{ text: 'User mints his profile with the basic information he wants to share.' },
		{
			text: 'User enhances this further by asking and answering questions which are generated by people and sorted by location.'
		},
		{
			text: 'User can find and connect with those that he resonates with based on eachothers meta profile.'
		}
	];
	const useCasesArr = [
		{
			title: 'Connecting',
			color: '#29ABE2',
			text: 'Allkinds meta profile can help dating/friending services enhance their algorithms with a cohesion score between their users as well as to give the users a freedom to choose their matches.'
		},
		{
			title: 'HR-tools',
			color: '#ED1E79',
			text: 'Hiring the right people is a key. Integrate Allkinds into your talent ecauisition ruitines and see how potential candidates resontate with your team or with any particular member of your team.'
		},
		{
			title: 'Productivity',
			color: '#522785',
			text: 'What makes epmployees happy - good relationships at work place. Allkinds can help your people to know each other better and create stronger social bonds at work place.'
		},
		{
			title: 'City marketplace',
			color: '#FBB03B',
			text: 'Same as we resonate with people - we resonate with places. Whether it is a bar, a restaurant, fitness studio - people want to find the right place and owners want to bring the right customers.'
		},
		{
			title: 'Social networks',
			color: '#F15A24',
			text: 'Whether its a social network for a college campus where students can discover each other on what matter to them, or a hyper local invitational city community network - built-in social graph will help.'
		},
		{
			title: 'Integrate with web2',
			color: '#0E031F',
			text: 'Want to see who is your real friend on Facebook? Attach meta profile to LinkedIn?'
		}
	];
</script>

<!-- was building each statement genrating these segment blocks but it got too complicated for its usecase
should be done alot cleaner with datatype structure objects I think -->

<Segment>
	<h1 slot="title">Find the right people</h1>
	<!-- 'Find your kind' also sounds fun -->
	<p slot="text1">
		Allkinds is a Web3 DAO social platform that helps you find meaningfull connections.
	</p>
	<p slot="text2">
		We propose an open protocol that tries to bring new standards for digital personality identity
		to social services.
	</p>
	<svelte:fragment slot="extra">
		<Button on:click={login}>Join Alpha #0</Button>
	</svelte:fragment>
	<svelte:fragment slot="img">
		<img src={Proto1} alt="Screenshot of Allkinds Dapp" />
	</svelte:fragment>
</Segment>

<Segment>
	<h2 slot="title" id="about">Your meta profile of values in Web3</h2>
	<p slot="text1">
		A Meta profile represents the user's personality in the Web3 world. People can compare their
		meta profiles against other people, companies, or places and find those who resonate more.
	</p>
	<p slot="text2">
		All data is encrypted and we use zkp algorithms to be able to compare meta-profiles without
		revealing the information behind it.
	</p>
</Segment>

<Segment>
	<h2 slot="title">How it works</h2>
	<svelte:fragment slot="extra">
		<Grid data={howWorksArr} ids={true} />
	</svelte:fragment>
</Segment>

<Segment>
	<h2 slot="title">Powered by ICP</h2>
	<p slot="text1">
		Allkinds is build on the
		<a class="text-purple-600 hover:underline" href="https://www.internetcomputer.org"
			>Internet Computer</a
		>
	</p>
</Segment>

<Segment>
	<h2 slot="title">Use cases</h2>
	<svelte:fragment slot="extra">
		<Grid data={useCasesArr} ids={false} />
	</svelte:fragment>
</Segment>

<Segment>
	<h2 slot="title">Allkinds protocol</h2>
	<p slot="text1">
		We plan to research both NLP/ML and semantic web ontology structures to understand
		questions/answers and build or update meta profiles out of it.
	</p>
	<p slot="text2">
		By building a standard for canisters containing user data it would greatly benefit the IC
		community but also allow easy integration with outside networks and apps using semantic data
		practices.
	</p>
</Segment>

<Segment>
	<h2 slot="title">Allkinds DAO</h2>
	<p slot="text1">
		We plan to integrate NNS to create a DAO which will be used to govern and decide the development
		for Allkinds.
	</p>
</Segment>

<Segment>
	<h2 slot="title" id="roadmap">Roadmap</h2>
	<p slot="text1">Coming soon...</p>
</Segment>

<Segment>
	<h2 slot="title" id="whitepaper">Whitepaper</h2>
	<p slot="text1">Coming soon...</p>
</Segment>

<Segment>
	<h2 slot="title" id="team">Team</h2>
	<p slot="text1">Coming soon...</p>
</Segment>

<Segment>
	<h2 slot="title" id="contact">Contact</h2>
	<p slot="text1">Coming soon...</p>
</Segment>
