[dependencies]
base = "0.10.4"
itertools = "0.2.1"
StableBuffer = "https://github.com/f0i/StableBuffer#main"
map = "9.0.1"
prng = "0.0.3"
bench = "1.0.0"

[toolchain]
moc = "0.10.4"
pocket-ic = "1.0.0"
